# Site settings
title: Know Me
email: team@knowmetools.com
description: > # this means to ignore newlines until "baseurl:"
  Site for Know Me LLC
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://knowmetools.com" # the base hostname & protocol for your site

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
markdown: kramdown

gems:
  - jekyll-assets
  - octopress-autoprefixer

# jekyll-assets settings
assets:
  sources:
    - _assets/images
    - _assets/javascript
    - _assets/stylesheets

  # minification
  js_compressor: uglifier
  css_compressor: sass