# Site settings
title: Know Me
email: team@knowmetools.com
description: > # this means to ignore newlines until "baseurl:"
  Site for Know Me LLC
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://knowmetools.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
