# Site settings
title: Know Me
email: team@knowmetools.com
description: > # this means to ignore newlines until "baseurl:"
  Site for Know Me LLC
baseurl: ""
url: "http://knowmetools.com"

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - "*.sublime-*"

markdown: kramdown

gems:
  - jekyll-assets
  - jekyll-sitemap

# jekyll-assets settings
assets:
  sources:
    - _assets/javascript
